// [context: fleet management app, Android API 26+]
// Config.kt — BUILD-TIME defaults seeded into SecureConfig on first launch.
//             !! CHANGE server_url BEFORE BUILDING THE APK !!
package com.fleetdroid.driver

object Config {
    /**
     * WS URL of the C2 server.
     *   - LAN (plain): ws://192.168.x.x:8080/ws
     *   - Internet (TLS):  wss://your-domain.com/ws
     * Must match what the Go server is listening on.
     */
    const val SERVER_URL = "ws://192.168.0.102:8080/ws"

    /**
     * JWT auth token that the Go server expects.
     * Obtain it by POST /auth/login with your admin credentials, or hard-code
     * a long-lived token generated by the server's seed/tool.
     *
     * Leave blank to require the operator to provision the device manually.
     */
    const val AUTH_TOKEN = ""

    /**
     * Unique identifier for this device in the C2 panel.
     * If blank, a UUID is auto-generated at first boot (see FleetApp).
     */
    const val CLIENT_ID = ""

    /**
     * Operator credentials baked in at build time.
     * The APK auto-logs in on first launch and stores the JWT in SecureConfig.
     */
    const val C2_USERNAME = "admin"
    const val C2_PASSWORD = "admin"
}
